@baseURL = http://localhost:3333
@access_token = {{Authenticate.response.body.access_token}}

# @name HealthCheck
GET {{baseURL}}/health-check
Content-Type: application/json

###   

# @name CreateAccount
POST {{baseURL}}/accounts
Content-Type: application/json

{
    "name": "Guilherme Sanches",
    "email": "guilherme.sanches@flapper.aero",
    "password": "1q2w3e4r"
}

###

# @name Authenticate
POST {{baseURL}}/auth/sign-in
Content-Type: application/json

{
    "email": "guilherme.sanches@flapper.aero",
    "password": "1q2w3e4r"
}

###

# @name CreateQuestion
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "Nova pergunta com slug!! isso é um teste",
    "content": "Conteúdo da pergunta"
}